# Generated by Django 4.1.5 on 2023-05-28 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_diary_image_alter_diary_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='image_video',
            field=models.ImageField(blank=True, null=True, upload_to='media/video_images/', verbose_name='動画のサムネイル'),
        ),
        migrations.AddField(
            model_name='diary',
            name='secret',
            field=models.BooleanField(default=True, verbose_name='内緒'),
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diary',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name='動画'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='本文'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='コメント')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.tag', verbose_name='タグ'),
        ),
    ]
