# Generated by Django 4.1.5 on 2023-03-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='本文'),
        ),
    ]
