# Generated by Django 4.1.5 on 2023-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_tag_diary_image_video_diary_secret_diary_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image_video',
            field=models.ImageField(blank=True, null=True, upload_to='video_images/', verbose_name='動画のサムネイル'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='動画'),
        ),
    ]
