# Generated by Django 4.1.5 on 2023-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_image_alter_diary_image_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image_video',
            field=models.ImageField(blank=True, null=True, upload_to='media/video_images/', verbose_name='動画のサムネイル'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name='動画'),
        ),
    ]
